---
title: Genética de poblaciones, 2025
date: today
date-format: "DD MMMM, YYYY"
author: 
  Mathias
abstract:
    Segundo parcial
abstractspacing: double
appendix: false
fontfamily: libertine
monofont: inconsolata
monofontoptions: scaled=.95
fontsize: 12pt
geometry: 
  - top=2cm
  - bottom=2cm
  - left=2cm
  - right=2cm
urlcolor: darkblues
highlight-style: arrow
format: 
    pdf:
      toc: false
      toc-depth: 2
      number-sections: true
      colorlinks: true
---

# Ejercicio

## A. Proponer un posible escenario de expansión geográfica de la especie y cómo podría ponerse a prueba dicha hipótesis. 

|  Estadístico                    |        Bosque            |            Pradera           |
|---------------------------------|--------------------------|------------------------------|
| Diversidad ($\pi$)              | Alto ($0.050 \pm 0.005$) |   Bajo ($0.025 \pm 0.003$)   |
| Sitios Segregantes ($\theta_{W}$​) | Alto ($0.053 \pm 0.003$) | Muy Bajo ($0.010 \pm 0.002$) |
| $F_{SC}$                        | Alto ($0.050 \pm 0.010$) | Bajo ($0.010 \pm 0.002$)     |
| Estructura ($F_{CT}$​)           |                  ($0.100 \pm 0.020$)                    |

### Escenario de Expansión Geográfica

El Bosque presenta una diversidad nucleotídica aproximadamente el doble que la Pradera $\pi = 0.050$ vs. $0.025$. La diversidad en el Bosque es consistente con una población grande y estable que esta en equilibrio demográfico durante tiempo, acumulando variación. En Pradera la diversidad nucleotidica es reducida a la mitad y con pocos sitios segregantes. Esta pérdida de variación es caracteristico de un cuello de botella o evento fundador.

En el bosque se observa $\theta_{W} \approx \pi$, lo que indica una distribución equilibrada de variantes raras y de las comunes, este patron es consistente para poblaciones que estan en equilibrio demográfico. Sin embargo, la Pradera tine pocos sitios segregantes y los alelos raros y nuevos fueron eliminados. Esto ultimo, es caracteristico de cuello de botella/efecto fundador.

Aunque no es posible calcular Tajima’s D con nuestros datos, se puede inferirse su signo. Usando solo la diferencia entre diversidad nucleotidica y sitios segregantes. Para el $Bosque = 0.050 - 0.053 = -0.003 \approx 0$, lo que corresponde equilibrio mutación-deriva, siendo estable durante tiempo. En contraste, la $Pradera = 0.025 - 0.010 = 0.015 > 0$, tiene las caracteristicas de un cuello de botella/efecto fundador que ocurrió hace un tiempo suficiente para que la deriva elimine los alelos raros y desplace las frecuencias restantes a valores intermedios.

Un escenario posible es que hay una población ancestral estable en el Bosque, deonde ocurrio un evento fundador hacia la Pradera acompañado de un cuello de botella. La deriva genética durante el cuello de botella eliminó los alelos raros y nuevos $\theta_{W}$ y $\pi$ bajo, pero mayor $\theta_{W}$​.

### Prueba de la Hipótesis Demográfica

Para poner a prueba la hipótesis de que el Bosque actúa como población estable, mientras que la población de la Pradera se formó a través de un evento de cuello de botella seguido de un periodo de expansión, con un flujo génico Bosque $\rightarrow$ Pradera, debemos utilizar diferentes  análisis, proporcionando distintos enfoques para entender la historia poblacional. 

En primer lugar, analizar la estructura genética con el $F_{CT}$ y $F_{SC}$ proporcionados. El $F_{CT}$ diferenciación moderada entre las dos áreas (Bosque vs. Pradera), compatible con el aislamiento por distancia. El Bosque presenta un $F_{SC}$ moderado, sugiriendo estructura local con cierto grado de aislamiento entre las subpoblaciones. En cambio, para Pradera muestra un $F_{SC}$ bajo, subpoblaciones entre si son homogeneas. Esta homogeneidad es caracteristica de una rápida mezcla.

Luego, para evaluar si son procesos demográficos o por selección, proponemos usar tests de neutralidad como Tajima’s D. Si los valores cercanos a cero en Bosque indicando neutralidad y desviados positivos en Pradera, patron uniforme en todo el genoma serían compatible con un proceso demográfico. En cambio, si esto es a nivel local estariamos ante un proceso por selección. Valores negativos podrían indicar expansion reciente o barrida selectiva (nivel local). Si estamos ante un proceso demográfico puede ser útil modelar el Espectro de Frecuencias Alélicas (SFS), permitiendo comparar directamente modelos demográficos e identificar cuál describe mejor los datos.

Finalmente, para evaluar la expansión, usamos el test $\psi$ desarrollado por Peter & Slatkin, diseñado para detectar expansiones recientes. Su señal direccional combinado con la señal especial, usando TDOA, permiten estimar el punto de origen de la expancion. Si el origen inferido se localiza en la región del Bosque, entonces tenemos evidencia directa en favor de la hipótesis Bosque $\rightarrow$ Pradera.

## B. ¿Qué podría esperarse para los genes candidatos a haber evolucionado bajo selección positiva en los siguientes escenarios?

### Gen 1: Selección Direccional en la Pradera (Pelajes Claros)

En este caso, se espera que el alelo favorecido en la Pradera haya generado una barrida selectiva (selective sweep) en la región que incluye al gen. Una barrida reciente reduce la variación genética local, teniendo un $\pi$ y $\theta_{W}$ que debe ser muy bajos, icluso $(\approx 0)$, mientras que el promedio genómico de Pradera debe ser mas alto. Además, bajo una barrida reciente se espera que Tajima’s D sea negativo $D \ll 0$ en la región del gen. Esto debe ser contrastante con el $D$ global de Pradera. Otra caractristica esperada es un desequilibrio de ligamiento (LD) extendido alrededor del alelo favorecido, el haplotipo tendrá una alta frecuencia y una gran longitud dado que no ha pasado tiempo suficiente para la recombinación.

### Gen 2: Selección Equilibradora en Ambos Ambientes (Concentración de Orina)

En este escenario, un mismo polimorfismo se mantiene por selección equilibradora tanto en Bosque como en Pradera. La seleccion equilibradora aumenta la diversidad local dado que se mantiene dos o más haplotipos en un largo periodo de tiempo. Por lo tanto, se espera que $\pi \gg 0$ en la región del gen, siendo más alto que el promedio genómico en ambas áreas. Además, el mantenimiento de variantes en frecuencias intermedias genera un patrón característico en el Espectro de Frecuencias Alelicas (SFS) exceso de alelos comunes (aumenta la panza de la distribucion). Esto se puede ver en Tajima's D con un $D \gg 0$ en la region del gen. Dado que la seleccion equilibradora favorece el mismo polimorfismo en ambos ambientes, no se espera divergencia grande entre Bosque y Pradera en este locus. Por lo tanto, el $F_{CT}$ local debe ser $\ll 0.100$ que el valor genomico promedio.

# Ejercicio

## Calcular los coeficientes de endocría (F) de los individuos m, I y k

### Endogamia del individuo m

El individuo m pertenece a la generación 900 en una población donde el tamaño efectivo varia cíclicamente 10 generaciones con N = 50, 10 generaciones con N = 200, 10 generaciones con N = 1000.

El ciclo de 30 generaciones se repite de forma estable. Tenemos un ciclo de 30 generaciones ($10$ a $N=50$, $10$ a $N=200$, $10$ a $N=1000$) que se repite. $m$ está en la generación $900$ $\rightarrow$ $900/30 = 30$ ciclos.

$\left(1-\frac{1}{2 \cdot 50}\right) = (0.99)^{10} \approx 0.9043821$ 

$\left(1-\frac{1}{2 \cdot 200}\right) = (0.9975)^{10} \approx 0.9752794$

$\left(1-\frac{1}{2 \cdot 1000}\right) = (0.9995)^{10} \approx 0.9950112$ 

Producto por ciclo $ciclo = ciclo1 \cdot ciclo2 \cdot ciclo3 \approx 0.87762498$

Luego de 30 ciclos $(ciclos)^{30} \approx 0.01991908$ siendo 

$F_{m} = 1 - 0.01991908 \approx 0.98008092$

El individuo m tiene un coeficiente de endogamia muy alto.

### Endogamia del individuo I

Consanguinidad entre primos integrando la endogamia de m

$R_{KH} = \left(\frac{1}{2}\right)^4(1 + F_{m})$ $\rightarrow$ $R_{KH} = \frac{1}{16}\cdot(1 + 0.98008092)$

$R_{KH} \approx 0.123755$

La endogamia de I hijo de K y H

$F_{I} = R_{KH}$

$R_{I} \approx 0.123755$

### Endogamia de los individuos K y H

Los padres de K y H son endogámicos, pero su pareja no es emparentada con con estos, por lo que los hijos K y H no es endogámico por parentesco.

$F_{K} = F_{H} = 0$

# Ejercicio

## A. Selección total contra recesivos

Se quiere econtrar el número de generaciones necesarias para bajar a la mitad la frecuencia del alelo

$q_{n} = \frac{1}{2}q_{0}$

La ecuación contra el recesivo es

$n=\frac{​q_{0}​−q_{n}​​}{q_{0}​q_{n}}$

Sustituyendo $q_{n} = \frac{1}{2}q_{0}$ en la ecuación contra el recesivo

$n=\frac{​q_{0}​−q_{0}/2​​}{q_{0}​(q_{0}/2)}$

Para el numerador usamos $q_{0}.1 = \frac{2}{2}q_{0}$ sustituimos

$\frac{2q_{0}}{2} - \frac{q_{0}}{2} = \frac{2q_{0} - q_{0}}{2} = \frac{q_{0}}{2}$

Entonces sustituimos

$n=\frac{q_{0}/2}{q_{0}^2/2}$; $n = q_{0}/q_{0}^2$

Finalmente, el número de generaciones para reducir a la mitad la frecuencia del alelo recesivo es el inverso de la frecuencia inicial.

$n = \frac{1}{q_{0}}$

## B. Selección parcial contra recesivos

La ecuación parcial contra el recesivo es

$sn=\frac{​q_{0}​−q_{n}​​}{q_{0}​q_{n}} + \ln \left[ \frac{q_{0}​(1-q_{n})}{q_{n}(​1-q_{0})} \right]$

Podemos sustituir el primer termino como en el anterior ejercicio A

$\frac{​q_{0}​−q_{n}​​}{q_{0}​q_{n}} = \frac{1}{q_{0}}$

sustituimos la siguiente expresion sabiendo que necesitamos bajar a la mitad la frecuencia del alelo $q_{n} = \frac{1}{2}q_{0}$

$\ln \left[ \frac{q_{0}​(1-q_{n})}{q_{n}(​1-q_{0})} \right] = \ln \left[ \frac{q_{0}​(1-(q_{0}/2))}{(q_{0}/2)(​1-q_{0})} \right]$

Para eliminar el $\frac{1}{2}$ multiplicamos por el reciproco $\frac{2}{1}$ multiplicando en el numerador y denominador

$\frac{q_{0}​(1-(q_{0}/2))}{(q_{0}/2)(​1-q_{0})} \cdot \frac{2}{2} = \frac{2-q_{0}}{1-q_{0}}$

Finalmente, Para despejar $n$, dividimos ambos lados de la ecuación por el coeficiente de selección $s$

$n= \frac{1}{s} \left(  \frac{1​​}{q_{0}} + \ln \left[ \frac{2-q_{0}}{​1-q_{0}} \right]\right)$

# geneRax

$E_{e} = p^L + p^S (E_{f}E_{g}) + p^D (E_{e}^2) + p^T (E_{e}E_{e})$

$E_{e} = \sum_{h} \in \mathscr{T}(e) \frac{E_{h}}{\lvert \mathscr{T}(e) \rvert}$

$[E_{e}]^{n} = p^L + p^S [E_{f}]^{n-1}[E_{g}^{n-1}] + p^D ([E_{e}]^{n-1})^{2} + p^T [E_{e}]^{n-1} \sum_{h} \in \mathscr{T}(e) [E_{e}]^{n-1}/\mathscr{T}(e)$